### ISSUE TITLE
Unknown function: strcharpart

### ISSUE THREAD

**Issue by K-Eo** [christoomey/vim-sort-motion#13]
Hi @christoomey, I have been using this plugin and is awesome.

Everything works fine but when I want to sort items inline `(foo, bar, baz)` I get an error `Unknown function: strcharpart` in vim 7.4.1689.

![screenshot from 2018-03-02 19-46-52](https://user-images.githubusercontent.com/3487347/36929236-8f48be5e-1e53-11e8-9f89-774b66cf2a08.png)

Apparently, the way to fix this bug is changing `strcharpart()` to `strpart()`.

**Comment by christoomey** [comment]
Hey @K-Eo, thanks for reporting. Mind opening a PR for the change?

**Comment by K-Eo** [comment]
@christoomey, PR on the way.

**Comment by christoomey** [comment]
Closed by https://github.com/christoomey/vim-sort-motion/pull/14. Thanks @K-Eo!
