### ISSUE TITLE
Works in Vim 8?

### ISSUE THREAD

**Issue by nicolas-rodriguez-globant** [christoomey/vim-sort-motion#18]
I'm using this Plugin with vim 8 but seems thats not work!, the message when I use the command `:gs4j` is:
`Not an editor command: gs4j`

**Comment by christoomey** [comment]
Hi Nicolas, the key sequence is meant to be used in normal mode, not command mode. The colon at the beginning puts you into command mode. Just hit escape a few times then type `gs4j` to sort down four lines. Hope that helps!
